### ISSUE TITLE
[FEATURE TASK] Services and controllers unit tests

### ISSUE THREAD

**Issue by mslowiak** [jmprathab/MyHome#100]
## Task description

There is a need to create unit tests for controllers

## Tasks

The following tasks will need to be carried out:

- [x]  CommunityController unit tests (#101)

- [x] HealthCheckController unit tests (#102)

- [x] HouseController unit tests (#103)

- [x] CommunitySDJpaService unit tests (#104)

- [x] HouseSDJpaService unit tests (#105)

- [x] UserSDJpaService unit tests (#106)
