### ISSUE TITLE
[FEATURE TASK] Relocate endpoints in api.yaml regarding to their responsibilities

### ISSUE THREAD

**Issue by mslowiak** [jmprathab/MyHome#228]
## ⚠️ Is your feature request related to a problem? Please describe

We want to have endpoints separated by feature and located in swagger via tags.

## 💡 Things need to be done:
- [x] - Add `useTags=true` flag in openapi-generator config #225 
- [x] - Fix typos connected with tags #227
- [x] - Analyze actual endpoints tags #226
- [x] - Move deleteBooking from AmenityController to BookingController #220 
- [x] - Move endpoint related to payments from communities tag to payments  #231 
- [ ] - Move endpoints related to houses from community tag #232
- [x] - Move endpoints related to amenities from community tag #233

**Comment by TimotheDavid** [comment]
hey @mslowiak  can I make it ? it will takes few hours
