### ISSUE TITLE
[FEATURE TASK] Add login endpoint to the schema

### ISSUE THREAD

**Issue by mslowiak** [jmprathab/MyHome#237]
## 🤚 Things needs to be done:
- [x] - Create new login endpoint schema for `auth/login` with controller #238 
- [x] - Update code on frontend side https://github.com/jmprathab/MyHome-Web/issues/119
- [x] - Delete old login filter (`MyHomeAuthenticationFilter`) #239 
- [x] - Unit tests for new login endpoint  #243
