### ISSUE TITLE
[FEATURE TASK] Amenity Management

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome#93]
## ⚠️ Is your feature request related to a problem? Please describe

* Add Amenities to a community. Example, Gym, Swimming Pool, Tennis Court.

## 💡 Describe the solution you'd like

Following are the sub-tasks

- [x] Add amenity JPA entity(#117)
- [x] Add an amenity to a community (#108)
- [x] Get a list of amenities within a given community (#109)
- [x] Get details of an amenity(#110)
- [x] Update an amenity(#111)
- [x] Delete an amenity(#112)

**Comment by mslowiak** [comment]
@jmprathab could you update the status of checkboxes in description?

**Comment by jmprathab** [comment]
> @jmprathab could you update the status of checkboxes in description?

Done.

**Comment by HristianIliev** [comment]
Can I take this up?

**Comment by mslowiak** [comment]
@jmprathab Is it a duplicate for #108 ?

**Comment by jmprathab** [comment]
@mslowiak #108 is the actual task under the umbrella of #93. I have updated the title to convey better.

**Comment by jmprathab** [comment]
> Can I take this up?

@HristianIliev All sub-tasks under this story are assigned to others. Please feel free to pick up some other open issue.

**Comment by jmprathab** [comment]
Marking the task as "Future complete". Every task under this story is completed.
