### ISSUE TITLE
[FEATURE TASK] Amenity booking management

### ISSUE THREAD

**Issue by jmprathab** [jmprathab/MyHome#94]
## ⚠️ Is your feature request related to a problem? Please describe

* House members should be able to book a slot for an amenity. Example, book tennis court from 10 AM to 11 AM.

## 💡 Describe the solution you'd like

* Can be taken up only after jmprathab/MyHome#93

## Sub-tasks

- [ ] Book an amenity(#113)
- [ ] Get all bookings for an amenity with an optional time range(#114)
- [x] Update an amenity booking(#115) - Note: closed this as no fix intended
- [x] Delete an amenity booking(#116)

**Comment by mslowiak** [comment]
@jmprathab could you update the status of checkboxes in description?

**Comment by jmprathab** [comment]
> @jmprathab could you update the status of checkboxes in description?

None of the sub-tasks is implemented I guess.

**Comment by douglas-oliveira-talkdesk** [comment]
Hello @jmprathab 👋 
Can I get this issue?

Thanks
